version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: crm-postgres-prod
    environment:
      POSTGRES_DB: crm_standard_prod
      POSTGRES_USER: ${DB_USER:-produser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strongpassword123}
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./backend/database/backup:/backup
    networks:
      - crm-prod-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-produser} -d crm_standard_prod"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: crm-redis-prod
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-strongredispassword123}
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    networks:
      - crm-prod-network
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-strongredispassword123}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local

networks:
  crm-prod-network:
    driver: bridge
