export const permissionMap: Record<string, Record<string, "A" | "R" | "N">> = {
  สี: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ติดตามกระบวนการขาย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  การติดตามตัวชี้วัดสำคัญ: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  คาดการณ์ยอดขาย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  รายงาน: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  การจัดการลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  กำหนดข้อมูลพื้นฐานลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  กลุ่มแท็ก: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  บทบาทลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  นิสัยลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  บันทึกกิจกรรม: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  dashboard: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  วิธีการชำระเงิน:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  สกุลเงิน:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ใบเสนอราคา:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  อนุมัติใบเสนอสินค้า:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ใบสั่งขาย:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  สินค้าทั้งหมด:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  กลุ่มสินค้า:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  หน่วยสินค้า:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  การจัดการข้อมูลบริษัท:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  พนักงาน:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  การจัดการทีม:{
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  }
};
